### ISSUE TITLE
Doesn't actually do anything?

### ISSUE THREAD

**Issue by javedbartlett** [myzb/SpecSpecificKeybinds#1]
I've installed the addon but nothing loads

**Comment by myzb** [comment]
You should get a notification every time you change specialization, telling you that the keybindings changed. Whatever key bindngs you currently have set will be your initial default for all other specs.

Only keybinds belonging to the default blizzard interface work. Addons that add extra elements that can be key bound store their key binds differently.

Anyway try the following and let me know:
1. Change the keybind for Action Button 1
2. Change Spec
3. Change keybind for Action Button 1 to something else
4. Switch back to the previous spec
5. Check if the keybind for Action Button 1 got restored
