### ISSUE TITLE
Keybinds not saving

### ISSUE THREAD

**Issue by Bizkit5050** [myzb/SpecSpecificKeybinds#3]
Hello. I'm using this addon to help me with bars that I have split up between different specs. I have bars 1 - 6 in Balance / Resto and bars 1 - 3 in Feral / Guardian being used. I use ElvUI, and every bar works perfectly with this addon and me using the /kb command in ElvUI to assign keybinds except when I swap from Feral or Guardian into Balance or Resto, bar 6 loses all of it's keybinds, but the other bars maintain the keybinds that I set. Is there something that I am doing wrong? Please, let me know. Thank you!

**Comment by myzb** [comment]
I don't use ElvUI but I do use Dominos for my actionbars. I had a similar issue where keybinds of one of my bars were not getting saved. The thing is that Dominos and probably ElvUI Bar 6 is an 'ElvUI only' bar. So the game does not properly track keybindings bound to that bar.

Last time I used ElvUI I think I saw an option within ElvUI itself to set specialization keybinds directly. If that is the case you may not need this addon or both addon may be interfering. 

In any case I think there are 3 ElvUI only bars. If it's an option for you I'd try to not use those bars.

**Comment by Davis24** [comment]
I also use elvui, I have noticed two keys that seem to unbind when I use it. 

V and Q. The rest of them are saving so it seems odd there are just a few keys not working.

**Comment by Klixxx** [comment]
I have same issue, some keys on my ElvUI bar 2 wont get saved... same happens with Action Bar Profiles...

**Comment by Klixxx** [comment]
And there is no saving for keybindings in ElvUI.. would love a fix for this, love the minimalism this addon gives.

**Comment by myzb** [comment]
Use elvui bars 1,3,4,5,6. Put binds that stay the same across specs on the other bars. I made a post about the issue with elvui on curseforge and also in the add-on FAQ.

**Comment by N6REJ** [comment]
even using bar "10" for the common bar it won't retain the bindings.  It seems things are not being written to the .lua properly.
[SavedVariables.zip](https://github.com/myzb/SpecSpecificKeybinds/files/6004876/SavedVariables.zip)
![WoWScrnShot_021821_114212](https://user-images.githubusercontent.com/1850089/108400965-7043bd80-71e1-11eb-87ba-8de6315b6a7b.jpg)
everytime I log back in I have to reset the f10,f11,f12 on bar 10
